//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FondFoxProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfel
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Stocks Stocks { get; set; }
        public virtual Users Users { get; set; }
    }
}
